### ISSUE TITLE
Update help&support page

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-docs#746]
### Description
It [suggests](https://docs.conda.io/en/latest/help-support.html#contribute-recipes-to-github) users can help by contributing recipes to https://github.com/conda/conda-recipes, but that repo is archived now. If anything, it should point to conda-forge?

### Tasks
- [x] Should this point to github.com/AnacondaRecipes/ (If not, where?) - AnacondaRecipes is a good place to get feedstocks, but not to contribute back to. Will link to AnacondaRecipes, conda-forge, and bioconda.
- [ ] Recommend a way this should work (the docs landing page will likely be replaced by conda.org work)
- [ ] Fix it if it's simple
