### ISSUE TITLE
update "Help and support"

### ISSUE THREAD

**Issue by rootsmusic** [conda/conda-docs#915]
### Checklist
- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?
[Help and support](https://docs.conda.io/en/latest/_sources/help-support.rst.txt) should be updated to:

- [ ] Replace "Google Groups" (which was closed) with [Discourse group](https://conda.discourse.group/).
- [ ] Add [Matrix chat](https://matrix.to/#/#conda:matrix.org).
- [ ] "Report bugs" section should clarify that [this repo](https://github.com/conda/conda-docs/blob/main/README.md) "includes documentation that is common for conda and conda-build" and "The documentation for each of those individual repositories can be found in their respective repos".
- [ ] Clarify when to use [conda's User Guide](https://docs.conda.io/projects/conda/en/stable/user-guide/index.html) and when [Anaconda Distribution's User Guide](https://docs.anaconda.com/free/anacondaorg/user-guide/). (see [comment](https://github.com/conda/conda/issues/13283#issuecomment-1831122901))
```[tasklist]
### Tasks
- [ ] https://github.com/conda/conda-docs/issues/798
```
